global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: pushgateway
    honor_timestamps: true
    honor_labels: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:9091
