on:
  push:
    branches: [example-app-insights]

name: Example AppInsights

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      otelcol:
        image: frigus02/tracebuild-example-app-insights-otelcol
        ports:
          - 4317:4317
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Tracebuild: Setup and capture start of Install toolchain"
        run: |
          curl -L -o tracebuild https://github.com/frigus02/tracebuild/releases/latest/download/tracebuild-linux-amd64
          chmod +x tracebuild
          echo "BUILD_START=$(./tracebuild now)" >>$GITHUB_ENV
          echo "BUILD_ID=$(./tracebuild id)" >>$GITHUB_ENV
          echo "STEP_TOOLCHAIN_START=$(./tracebuild now)" >>$GITHUB_ENV
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Tracebuild: Report Install toolchain"
        run: ./tracebuild step --build $BUILD_ID --id $(./tracebuild id) --start-time $STEP_TOOLCHAIN_START --name "Install toolchain"
      - name: Run cargo test
        run: ./tracebuild cmd --build $BUILD_ID -- cargo test --all-features
      - name: Run cargo fmt
        run: ./tracebuild cmd --build $BUILD_ID -- cargo fmt -- --check
      - name: Run cargo clippy
        run: ./tracebuild cmd --build $BUILD_ID -- cargo clippy --all-features
      - name: "Tracebuild: Report build"
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
        run: |
          if [[ "$JOB_STATUS" == "success" ]]; then
            BUILD_STATUS=success
          else
            BUILD_STATUS=failure
          fi
          ./tracebuild build --id $BUILD_ID --start-time $BUILD_START --name "tracebuild - Example AppInsights" --branch $GITHUB_REF --commit $GITHUB_SHA --status $BUILD_STATUS
